all:
	gcc -g -Wall -o modified_pth_mat_vect_rand_split modified_pth_mat_vect_rand_split.c -lpthread

modified_pth_mat_vect_rand_split:
	gcc -g -Wall -o modified_pth_mat_vect_rand_split modified_pth_mat_vect_rand_split.c -lpthread

run: modified_pth_mat_vect_rand_split
	./modified_pth_mat_vect_rand_split

clean:
	rm modified_pth_mat_vect_rand_split
